version: '3.8'

x-common-options: &common-options
  restart: always
  extra_hosts:
    - "host.docker.internal:host-gateway"
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./settings.toml:/app/settings.toml:ro
      - ./.secrets.docker.toml:/app/.secrets.toml:ro
    <<: *common-options
  nginx:
    image: nginx:alpine
    ports:
      - "35080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - app
    environment:
      - API_HOST=host.docker.internal
      - API_PORT=8234
    <<: *common-options
