dynaconf_merge = true

[mongo]
url = "mongodb://localhost:27017/woc"

[clickhouse]
url = "clickhouse://localhost:9000/woc"

[github]
# https://github.com/settings/applications/new
app_id = false  
app_secret = "xxx"

[microsoft]
# https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade/quickStartType~/null/sourceType/Microsoft_AAD_IAM
app_id = false  # false to disable this endpoint
priv_key = "-----BEGIN PRIVATE KEY-----\n..."
thumbprint = "AA11BB22CC33DD44EE55FF66AA77BB88CC99DD00"